package wow

type CharacterStats struct {
	Health int
	PowerType string
	Power int
	Str int
	Agi int
	Sta int
	Int int
	Spr int
	AttackPower int
	RangedAttackPower int
	PvpResilienceBonus float32
	Mastery float32
	MasteryRating int
	Crit float32
	CritRating int
	HitPercent float32
	HitRating int
	Haste float32
	HasteRating int
	HasteRatingPercent float32
	ExpertiseRating int
	SpellPower int
	SpellPen int
	SpellCrit float32
	SpellCritRating int
	SpellHitPercent float32
	SpellHitRating int
	Mana5 float32
	Mana5Combat float32
	SpellHaste float32
	SpellHasteRating int
	SpellHasteRatingPercent float32
	Armor int
	Dodge float32
	DodgeRating int
	Parry float32
	ParryRating int
	Block float32
	BlockRating int
	PvpResilience float32
	PvpResilienceRating int
	MainHandDmgMin float32
	MainHandDmgMax float32
	MainHandSpeed float32
	MainHandDps float32
	MainHandExpertise float32
	OffHandDmgMin float32
	OffHandDmgMax float32
	OffHandSpeed float32
	OffHandDps float32
	OffHandExpertise float32
	RangedDmgMin float32
	RangedDmgMax float32
	RangedSpeed float32
	RangedDps float32
	RangedExpertise float32
	RangedCrit float32
	RangedCritRating int
	RangedHitPercent float32
	RangedHitRating int
	RangedHaste float32
	RangedHasteRating int
	RangedHasteRatingPercent float32
	PvpPower float32
	PvpPowerRating int
	PvpPowerDamage float32
	PvpPowerHealing float32
}
